from pydantic import BaseModel


# =========================
# BASE MODEL (SHARED FIELDS)
# =========================
# Contains common fields used across multiple task models
# This avoids repeating the same attributes in multiple classes
class TaskBase(BaseModel):
    task_name: str
    task_desc: str | None = None   # Optional field (can be None)
    assigned_to: str


# =========================
# CREATE MODEL (INPUT)
# =========================
# Used when creating a new task (POST request)
# Inherits all fields from TaskBase
# No additional fields needed (id is auto-generated in DB)
class TaskCreate(TaskBase):
    pass


# =========================
# RESPONSE MODEL (OUTPUT)
# =========================
# Used when returning task data from API (GET requests)
# Includes additional fields generated by database
class Task(TaskBase):
    task_id: int        # ID from database (auto-incremented)
    completed: bool     # Task completion status (converted from 0/1)


# =========================
# UPDATE MODEL (INPUT)
# =========================
# Used when updating an existing task (PATCH request)
# Includes all fields that can be modified
class TaskUpdate(BaseModel):
    task_name: str
    task_desc: str
    assigned_to: str
    completed: bool